name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Dokku
        uses: dokku/github-action@v1.0.1
        with:
          git_push_flags: '--force'
          git_remote_url: ${{ secrets.DOKKU_GIT_REMOTE_URL }}
          ssh_private_key:
            ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
